### PR TITLE
Fix PCB issues

### PR DESCRIPTION
**Pull request by nikitalita**
I ran into some issues when ordering the PCB from JLCPCB, so I had to make some minor adjustments:

1) Changed the footprint for the toslink ports to the T8 variation vs. the T10. 
I can't find the PLR135/T10 part anywhere, and JLCPCB only had the T8. The only difference is the addition of two NPTH for the plastic mounting feet, so either the T10 or T8 variations can be used.

2) Fix the USB-C port rotation for the POS file; it is flipped 180 degrees in the JLCPCB render

3) Move power traces away from board edge
[The JLCPCB capabilities](https://jlcpcb.com/capabilities/pcb-capabilities) section says that traces must be >=.2mm from the edge:
image

So I just moved the power traces about .1mm; the only thing that it might cause issue with is that they're closer to the shield PTHs, but they still have about .4mm clearance to copper.

4) Adjusted the board width for TOSLINK port clearance so that it can be flush with the case.

BTW, you may want to update your JLCPCB plugin, I note that the part assignments file was in a different format.

### CODE REVIEW

**Comment by hansfbaier** [comment]
I got the T10 on AliExpress then, but you found some on JLCPCB, that's much better! Thanks for the changes!

**Comment by hansfbaier** [comment]
Actually, why we are at it the USB PHYs could use length matching.
They work fine with Cyclone IV because of its slow rise times,
but on faster FPGAs like Artix 7 they don't work properly.
Did you already submit your order?

**Comment by hansfbaier** [comment]
Wait a minute I am doing the length matching just now.

**Comment by nikitalita** [comment]
noy yet, I wisely decided to wait until you reviewed it ;)

**Comment by hansfbaier** [comment]
@nikitalita I just pushed the length matched version. You might want to have another look at it. DRC pass here.

**Comment by hansfbaier** [comment]
@nikitalita Still wait a minute, I still need to adjust the diff pair traces of the upper PHY

**Comment by hansfbaier** [comment]
@nikitalita OK now it should be good.

**Comment by hansfbaier** [comment]
@nikitalita  Let me know when you get your board. I still need to write the platform definition for the Cyclone IV GX board.
I have the board at home, but didn't try it yet on the audio interface IIRC.

**Comment by nikitalita** [comment]
Ok, will do!

**Pull request merged**
